### ISSUE TITLE
Destination path does not support CIFS path

### ISSUE THREAD

**Issue by gsly** [yaser01/mkv-muxing-batch-gui#104]
The source path for videos supports a CIFS path, however the destination path does not.  

Code checks for a mapped drive letter in Windows.

**Comment by SIMAV8** [comment]
Thanks for this - I was giving MMBG a test drive and nothing was happening, was about to go back to batch files when saw your post.   I was using \\nas\staging\bla\ as source (SMB to a NAS), which doesn't work (for me, doesn't work in any "Folder" under any tab).    But, assign a drive letter, and problem solved.

Back to batch files though actually... cause
 - all the subtitle files are named the same, but in separate folders with the source
 - MMBG doesn't allow any duplicate file names, even though path different
 - and the "Track enabled" flag comes out Yes, I need them to be no

But, to the author, thanks - looks like a good program, just not fit for my particular purposes.   Perhaps a warning message when drag-n-dropping files and no results, I thought program was broken since nothing apparent was happening - really my dragged files were being actively discarded.

**Comment by yaser01** [comment]
Been working on this @gsly

**Comment by yaser01** [comment]
@SIMAV8  what do you mean by 

> and the "Track enabled" flag comes out Yes, I need them to be no

for the point   
> MMBG doesn't allow any duplicate file names, even though path different

duplicates are not allowed cause it will make names list confusing to user 
i may add to show the source path but don't want to make the gui ugly :D
maybe thinking of a way to add it  in upcoming updates not the next one indeed .

**Comment by SIMAV8** [comment]
Wow, you read the posts and comments!  Appreciate that,

I’m traveling for a week and only have cell, but if use MKVtoolnix gui, in
right subtitle pane the two items right below where type in name like
English or Spanish, there’s two items which default to Yes.  The top item
which MMBG can change to No keeps subs from being displayed by default -
though toggling both to No makes things work better with certain players;
Roku specifically in my use case (makes the Roku * function, closed
captioning, work consistently well)

It’s not critical, easily sorted with a quick script afterwards.

The dupe file names are much more of a hindrance; video I’m adding subs too
are little snippets for like a waiting area info panel.  The videos are in
folders like scene1\vid1.mkv and the subs in another folder scene1\subs\
and files are named English.srt, Spanish.srt - so if I receive like 30
videos, then I have 30 English.srt or 30 spanish.

Thanks again, I appreciate your response and hard work on this project!

**Comment by yaser01** [comment]
@SIMAV8 Thanks again for well explanation
for track enabled flag this may be added in next updates not 2.4 because it's almost done..
same thing for duplicates files 
for you now  you can quickly rename your files using some bulk rename tool then use MMBG 
a solution could be made is to enable duplicates with viewing the full path 
and letting the use either show files' names only or files' names with their full path
this also will no be added in 2.4 at least 
but will be working on it in following updates
Have a nice day and thanks for your good suggestions :D

**Comment by eddilara** [comment]
use renamer
https://www.den4b.com/products/renamer
its what I use to rename batch files

**Comment by SIMAV8** [comment]
I will be pleased to try the new version!   Thank you!

**Comment by yaser01** [comment]
Try 2.4 Update :D
